"""One-off backfill: re-run identify_sides() and generate_source_guidance() for
every existing active topic, using the new search-grounded versions instead of
whatever generated the topic's stored sides_json/source_guidance originally.

Why this exists: identify_sides()/generate_source_guidance() only ever run at
topic creation or on a description edit (see research.py) — they never
retroactively re-run on their own. Topics created before 2026-06-23 may have
sides/guidance generated by the old, ungrounded version (a pure LLM guess with
no web search), which is known to sometimes mis-attribute wire services
(BBC/Reuters/etc.) to one side instead of leaving them for the general query.

Defaults to a dry run — prints old vs. new for every topic, writes nothing.
Pass --apply to actually update the database. Always backs up the old values
to a timestamped JSON file before writing, so this is reversible.

    uv run python scripts/backfill_sides.py              # dry run, all topics
    uv run python scripts/backfill_sides.py --apply       # actually update, all topics
    uv run python scripts/backfill_sides.py --topic "Belarus Politics" --apply  # one topic only

--topic is useful for re-running a single topic that landed on a flaky result —
identify_sides()/generate_source_guidance() call live, search-grounded models,
so re-running the same topic can legitimately produce a different result each
time (confirmed: rerunning a known-good conflict topic 3x can occasionally
return an empty/worse result on one try even though it's correct the other two).
"""

from __future__ import annotations

import argparse
import asyncio
import json
from datetime import UTC, datetime
from pathlib import Path

from elephant import research, store

_BACKUP_DIR = Path(__file__).parent / "backfill_backups"


async def main(apply: bool, topic_filter: str | None) -> None:
    topics = await store.get_all_active_topics()
    if topic_filter:
        topics = [t for t in topics if t.name == topic_filter]
        if not topics:
            print(f"No active topic named {topic_filter!r} found.")
            return
    print(f"{len(topics)} active topic(s) found.\n")

    backups: list[dict[str, object]] = []

    for topic in topics:
        old_sides = [s.name for s in topic.sides]
        old_guidance = topic.source_guidance
        old_outlets = topic.default_outlets

        new_sides = await research.identify_sides(topic.description or topic.name, topic.name)
        new_guidance = await research.generate_source_guidance(
            topic.description or topic.name, topic.name
        )

        # identify_sides() is a live, non-deterministic grounded call — it has
        # known flakiness on conflict topics that DO have real sides (confirmed
        # with Belarus Politics earlier: re-running a known-good topic 3x can
        # occasionally come back empty even though it's correct the other two
        # times). Never let an empty result silently erase sides that were
        # previously found — that's much more likely a flaky miss than a
        # genuine "this topic has no sides after all".
        sides_suspect = old_sides and not new_sides
        if sides_suspect:
            print(f"  ⚠ sides came back empty but were previously {old_sides!r}")
            print("    SKIPPING sides_json overwrite (likely flaky) — keeping existing value")

        print(f"=== {topic.name} ===")
        print(f"  sides:    {old_sides!r} -> {[s.name for s in new_sides]!r}")
        for s in new_sides:
            print(f"    {s.name}: {s.outlets}")
        print(f"  guidance: {(old_guidance or '')[:80]!r}")
        print(f"         -> {new_guidance.instructions[:80]!r}")
        print(f"  default_outlets: {old_outlets!r} -> {new_guidance.outlets!r}")
        print()

        backups.append(
            {
                "topic_id": str(topic.id),
                "name": topic.name,
                "old_sides_json": topic.sides_json,
                "old_source_guidance": old_guidance,
                "old_default_outlets": old_outlets,
            }
        )

        if apply:
            update_fields: dict[str, object] = {
                "source_guidance": new_guidance.instructions,
                "default_outlets": new_guidance.outlets,
            }
            if not sides_suspect:
                update_fields["sides_json"] = json.dumps([s.model_dump() for s in new_sides])
            await store.update_topic(topic.id, **update_fields)

    if apply:
        _BACKUP_DIR.mkdir(exist_ok=True)
        stamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
        backup_path = _BACKUP_DIR / f"sides_backup_{stamp}.json"
        backup_path.write_text(json.dumps(backups, indent=2))
        print(f"Applied. Old values backed up to {backup_path}")
    else:
        print("Dry run only — no changes written. Pass --apply to update the database.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Actually write changes to the DB")
    parser.add_argument("--topic", default=None, help="Only process the topic with this exact name")
    args = parser.parse_args()
    asyncio.run(main(args.apply, args.topic))
